### PR TITLE
feat(XMLHttpRequest.upload) - Added the option of supplying various upload callbacks for storeInstances.

### PR DESCRIPTION
**Pull request by jbocce**
The changes allow for the optional tracking of the upload progress for any call to `_httpRequest` - in particular to facilitate tracking the progress of `storeInstances`.

### CODE REVIEW

**Comment by pieper** [comment]
Like https://github.com/dcmjs-org/dicomweb-client/pull/76, this looks good but adding a test would be good.

**Comment by jbocce** [comment]
> Like #76, this looks good but adding a test would be good.

Thank you so much for the review. When I run `npm test` on my Windows machine I get an error. Furthermore, the changes occur mid-flight for the request and the test would require a DICOM upload so the tests would not be that straightforward in this case.

**Comment by pieper** [comment]
After merging #76 there's a conflict - could you resolve it and then I'll merge this

**Comment by jbocce** [comment]
> After merging #76 there's a conflict - could you resolve it and then I'll merge this

Thanks for merging #76. I will resolve and let you know.

**Comment by jbocce** [comment]
Hi @pieper. I have resolved the conflicts and it should be good for you to have a look at. Thanks so much once again.

**Comment by pieper** [comment]
Thinking about this and #76  I was thinking it could be a cleaner API to just add a `request` parameter so that the user can add their own event listeners.  We could provide an example that shows how to get progress and/or abort the request.  I think this would be better than adding all these extra options here since they aren't really proper to dicomweb but really just http.

I don't like changing the API once we've merged but since we haven't released yet I don't think it would hurt to revert this and expose just the simpler API.

What do you think @jbocce and @sedghi?

**Comment by pieper** [comment]
To be more specific, I mean changing this line:

https://github.com/jbocce/dicomweb-client/blob/47f56fa3a4e01992372db606c01c15b42718484b/src/api.js#L171

to be something like 
```
      if ('request' in options) {
        request = options.request;
      } else {
       request = new XMLHttpRequest();
     }
```

**Pull request merged**
