### PR TITLE
feat(api): replaced upload callbacks and abort signal with an HTTP request object

### PR DESCRIPTION
**Pull request by jbocce**
Replaced the optional uploadCallbacks and AbortSignal objects for storeInstances with an optional XMLHttpRequest.
If present, the request will be used. Otherwise a request will be instantiated as before.
This allows for customizations to be made to the request without cluttering the dicomweb-client code.

Updated the readme with an example for how the changes might get used.

### CODE REVIEW

**Comment by jbocce** [comment]
@pieper I have incorporated your feedback into this PR. Please have a look at your earliest convenience. If you could also please double check that I have the semantic commit messages correct then that would be terrific.

FYI @sedghi.

**Review by pieper — APPROVED** [review]
Very nice - thank you! 👍

**Comment by jbocce** [comment]
> @jbocce it looks like we need to set up auto-publish for this repo like @richard-viney did for dcmjs. I've never done this before, do you think you could do it?
> 
> [dcmjs-org/dcmjs@2e61f0a](https://github.com/dcmjs-org/dcmjs/commit/2e61f0ad003208effd13c1d3c54331bf0bf84671)

Sorry, neither have I done it before. @sedghi any ideas? Does this mean we won't have a release until we do this?

**Comment by pieper** [comment]
We can do the release manually if needed (I'll have to remember how) but I thought it would be cleaner to have this set up in parallel with dcmjs.  I think that's how @dannyrb had set it up originally.

**Comment by pieper** [comment]
@hackermd who made the most recent release may also be able to help.

**Pull request merged**
